name: Momentum Scanner (3x >5%)

on:
  workflow_dispatch:   # lets you run it manually
  schedule:
    - cron: "0 13 * * 1-5"   # runs every weekday at 1pm UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance requests

      - name: Run momentum scanner
        run: python momentum_scan.py
